COPY aircrafts(icao24,
  registration,
  manufacturericao,
  manufacturer_name,
  model,
  type_code,
  serial_number,
  line_number,
  aircraft_type,
  operator,
  operator_call_sign,
  operator_icao,
  operator_iata,
  owner,
  test_reg,
  registered,
  reg_until,
  status,
  built,
  first_flight_date,
  seat_configuration,
  engines,
  modes,
  adsb,
  acars,
  notes)
from '/data/aircraft-database.csv' DELIMITER ',' CSV HEADER;
