version: '3'

#https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/full-stack.yml

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - './data/postgres:/var/lib/postgresql/data'
    - './aircraft-database.csv:/data/aircraft-database.csv'
    - './aircraft-database.sql:/data/aircraft-database.sql'
    ports:
    - 5432:5432
    networks:
    - fit

networks:
  fit:
    external: true
